pipeline {

  agent 
    //node { label 'web'}
    label 'JAVA'

  stages{
        
    stage('Download Dependencies'){
      //agent{
        //node {label 'Built-In Node'}
        //label 'MASTER'
      //}
      steps{
        sh 'echo Download Dependencies'
        
      }
    }

    stage('Find Bugs') {
      //agent {
        //node {label 'web'}
        //label 'JAVA'
      //}
      steps{
        sh 'echo Find Bugs'
      }
    }

    stage('Test cases'){
      steps{
        sh 'echo Test cases'
      }
    }
  }

}
